taschenrechner: taschenrechner.o stack.o
	gcc -o taschenrechner taschenrechner.o stack.o

taschenrechner.o: taschenrechner.c stack.h
	gcc -o taschenrechner.o -c taschenrechner.c

stack.o: stack.c
	gcc -o stack.o -c stack.c
